### ISSUE TITLE
This app has gone over its resource limits.

### ISSUE THREAD

**Issue by hetleo** [tylerjrichards/streamlit_goodreads_app#15]
### Description

![IMG_7214](https://github.com/tylerjrichards/streamlit_goodreads_app/assets/18065082/b55bba7d-17a0-4196-ad3a-cffe0b3af108)

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by tylerjrichards** [comment]
fixed, thank you!
