### ISSUE TITLE
App is in error state in Streamlit gallery

### ISSUE THREAD

**Issue by sfc-gh-asaini** [tylerjrichards/streamlit_goodreads_app#20]
<img width="867" alt="Screenshot 2024-03-18 at 10 52 28 AM" src="https://github.com/tylerjrichards/streamlit_goodreads_app/assets/110130910/9f376f44-5ef9-483c-981b-68457767184f">

cc: @tylerjrichards @sfc-gh-trichards

**Comment by tylerjrichards** [comment]
fixed, thanks Abhi!
