### ISSUE TITLE
404 to demo

### ISSUE THREAD

**Issue by leebrian** [tylerjrichards/streamlit_goodreads_app#3]
Hello, this demo seems cool and when I tried to click on the [link in your readme](http://www.tylerjrichards.com/book_reco.html) I get a 404 instead of seeing the demo. 

Not a big issue, but wanted to help in case you weren’t aware. Your project is featured on the [streamlit home page](https://streamlit.io/) and that’s how I found you.

**Comment by tylerjrichards** [comment]
hey leebrian, thanks for noticing this and filing an issue! Appreciate it. I've fixed this, it was just sending to the wrong url.
