### ISSUE TITLE
Book list recommendation: Incorrect URL

### ISSUE THREAD

**Issue by jordan-pierre** [tylerjrichards/streamlit_goodreads_app#6]
The app says I've read the most books in common with "keith rabois" but the URL to find their book list directs to "https://www.mostrecommendedbooks.com/naval-ravikant-books".  The "vinod khosla" link is correct.

I'm definitely a big fan of Naval, but I'd like to checkout this Keith Rabois guy too.

**Comment by tylerjrichards** [comment]
Hey @jordan-pierre, I finally got around to figuring out and fixing this bug, this was a weird edge case that should be fixed now (just pushed the fix to GitHub, so Streamlit will re-compile the app in the next few minutes). Appreciate it!
