### ISSUE TITLE
Youngest and oldest books

### ISSUE THREAD

**Issue by dbogt** [tylerjrichards/streamlit_goodreads_app#8]
I think the youngest/oldest books variables need to be flipped, since in the first sort you are showing the "newest"/most recent publication year at top (descending order):
row = df.sort_values(by='book.publication_year', ascending=False).head(1)
oldest_book = row['book.title_without_series'].iloc[0]
row_young = df.sort_values(by='book.publication_year').head(1)
youngest_book = row_young['book.title_without_series'].iloc[0]

I think it should be:
row = df.sort_values(by='book.publication_year', ascending=False).head(1)
**youngest_book** = row['book.title_without_series'].iloc[0]
row_young = df.sort_values(by='book.publication_year').head(1)
**oldest_book** = row_young['book.title_without_series'].iloc[0]

**Comment by tylerjrichards** [comment]
hey @dbogt, I think you're right! I was confused by it because the publication year is not actually correct for most of the books on Goodreads. Fixing rn

**Comment by tylerjrichards** [comment]
Fixed this here https://github.com/tylerjrichards/streamlit_goodreads_app/commit/5d7af88ff9b58293f856a383f5edfec8cfda1915, closing!
